apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onyx.fullname" . }}-env
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
data:
  INTERNAL_URL: "http://{{ include "onyx.fullname" . }}-api:{{ .Values.api.service.port }}"
  POSTGRES_HOST: "{{ include "onyx.fullname" . }}-postgresql"
  {{- if .Values.vectorDB.enabled }}
  DISABLE_VECTOR_DB: "false"
  VESPA_HOST: "{{ include "onyx.fullname" . }}-vespa-0.{{ include "onyx.fullname" . }}-vespa.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_HOST: "{{ include "onyx.fullname" . }}-redis"
  MODEL_SERVER_HOST: "{{ include "onyx.fullname" . }}-inference-model"
  INDEXING_MODEL_SERVER_HOST: "{{ include "onyx.fullname" . }}-indexing-model"
  {{- else }}
  DISABLE_VECTOR_DB: "true"
  MODEL_SERVER_HOST: ""
  CACHE_BACKEND: "postgres"
  AUTH_BACKEND: "postgres"
  FILE_STORE_BACKEND: "postgres"
  {{- end }}
  {{- range $key, $value := .Values.config }}
  {{- if not (empty $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
