{{- if and .Values.vectorDB.enabled (gt (int .Values.indexingModel.replicaCount) 0) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyx.fullname" . }}-indexing-model
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexing-model
spec:
  replicas: {{ .Values.indexingModel.replicaCount }}
  selector:
    matchLabels:
      {{- include "onyx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: indexing-model
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "onyx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: indexing-model
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "onyx.podSecurityContext" . | nindent 8 }}
      containers:
        - name: model-server
          image: "{{ .Values.indexingModel.image.repository }}:{{ .Values.indexingModel.image.tag | default .Values.global.version }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          securityContext:
            {{- include "onyx.containerSecurityContext" . | nindent 12 }}
          command:
            - uvicorn
            - model_server.main:app
            - --host
            - "0.0.0.0"
            - --port
            - {{ .Values.indexingModel.containerPort | quote }}
            - --limit-concurrency
            - {{ .Values.indexingModel.limitConcurrency | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.indexingModel.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "onyx.fullname" . }}-env
          env:
            - name: INDEXING_ONLY
              value: "True"
            {{- include "onyx.backendEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.indexingModel.resources | nindent 12 }}
{{- end }}
