{{- if .Values.vectorDB.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onyx.fullname" . }}-vespa
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: vespa
  annotations: {}
{{- end }}
