apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyx.fullname" . }}-webserver
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
spec:
  replicas: {{ .Values.webserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "onyx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webserver
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "onyx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "onyx.podSecurityContext" . | nindent 8 }}
      containers:
        - name: webserver
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag | default .Values.global.version }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          securityContext:
            {{- include "onyx.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.webserver.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "onyx.fullname" . }}-env
          env:
            {{- include "onyx.backendEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.webserver.resources | nindent 12 }}
